# Generated by Django 5.2.17 on 2026-09-15 22:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("catalog", "0001_initial"),
        ("warehouses", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="StockMovement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "flow",
                    models.CharField(
                        choices=[("receipt", "Receipt"), ("issue", "Issue"), ("adjustment", "Adjustment")],
                        max_length=16,
                    ),
                ),
                ("direction", models.CharField(choices=[("in", "In"), ("out", "Out")], max_length=8)),
                ("quantity", models.DecimalField(decimal_places=3, max_digits=12)),
                ("reason", models.CharField(max_length=500)),
                ("recorded_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending consent"),
                            ("applied", "Applied"),
                            ("cancelled", "Cancelled"),
                        ],
                        db_index=True,
                        default="applied",
                        max_length=10,
                    ),
                ),
                ("requires_override", models.BooleanField(default=False)),
                ("override_at", models.DateTimeField(blank=True, null=True)),
                ("reconciliation_ref", models.CharField(blank=True, max_length=100)),
                (
                    "location",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="movements",
                        to="warehouses.location",
                    ),
                ),
                (
                    "override_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="movements",
                        to="catalog.product",
                    ),
                ),
                (
                    "recorded_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="movements",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-recorded_at"],
                "indexes": [
                    models.Index(
                        fields=["product", "location", "recorded_at"], name="movements_s_product_d9fa23_idx"
                    ),
                    models.Index(fields=["flow", "recorded_at"], name="movements_s_flow_918a32_idx"),
                ],
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(("quantity__gt", 0)), name="movements_quantity_positive"
                    )
                ],
            },
        ),
    ]
