# Generated by Django 5.2.17 on 2026-09-15 22:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("movements", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="stockmovement",
            name="unit_cost",
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
    ]
